version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
  test:
    jobs:
      - node/test
  lint:
    jobs:
      - node/run:
          npm-run: check:lint 
  format:
    jobs:
      - node/run:
          npm-run: check:format 