version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
  check:
    jobs:
      - node/test:
          test-results-for: jest
      - node/run:
          name: lint
          npm-run: check:lint 
      - node/run:
          name: format
          npm-run: check:format 
      